### ISSUE TITLE
Support Multiple GitFS-backed Policy Modules

### ISSUE THREAD

**Issue by nickgarber** [genesis-matrix/gema-ctl#1]
https://github.com/amendlik/gitstack-pillar/blob/develop/docs/configuration.md

This will enable a policy designer to group policy into modules/repos according to whatever meaningful distinctions might exist.

**Comment by nickgarber** [comment]
Introduce '_policy_<namespace>' directories into policy modules.
This allows for the freedom to organize policy-content into whatever module-location are meaningful and helpful.

**Comment by nickgarber** [comment]
WIP

```
ext_pillar:
  - gitstack: 
    - master https://github.com/genesis-matrix/gema-plr-core.git:
      - root: _policy_core
      - stack:
        - pillarstack.cfg
        - pillarstack.cfg
        - pillarstack.cfg
        - pillarstack.cfg
        - pillarstack.cfg
    - master https://github.com/genesis-matrix/gema-plr-contrib.git:
      - root: _policy_contrib
      - stack:
        - pillarstack.cfg
        - pillarstack.cfg
        - pillarstack.cfg
        - pillarstack.cfg
        - pillarstack.cfg
    - master https://github.com/genesis-matrix/gema-plr-sitelocal.git:
      - root: _policy_sitelocal
      - stack:
        - pillarstack.cfg
        - pillarstack.cfg
        - pillarstack.cfg
        - pillarstack.cfg
        - pillarstack.cfg
```
